#!/bin/python3
from tkinter import Tk as App
from tkinter import *
import os
from pathlib import Path


def GitCommitButton():
	os.system(f'cd {Path} ; git add * ; git commit -a -m "committed with python3" ; git pull ; git push ')
	print(f"==========GitCommitButton() is finneshed. Git Center ready for the next comannd==========")
def GitPullButton():
	os.system(f"cd {Path} ; git pull")
	print(f"==========GitPullButton() is finneshed. Git Center ready for the next comannd==========")
def ChangePathButton():
	Path = input("Repository Path (start with / or ~): ")
	App.title(f"{Path} - Git Center")
	print(f"==========ChangePathButton() is finneshed. Git Center ready for the next comannd==========")


git_path_local = Path.cwd()

App = App()
App.title("python3.11 - Git Center")
Path = git_path_local
App.title(f"{Path} - Git Center")
GitCommit = Button(App, text="Git Commit" , command=GitCommitButton)
GitCommit.pack()
GitPull = Button(App, text="Git Pull" , command=GitPullButton)
GitPull.pack()
ChangePath = Button(App, text="Change Path", command=ChangePathButton)
ChangePath.pack()
TextLabel = Label(App, text="								Please Start this app with a terminal									")
TextLabel.pack()
App.mainloop()
